### ISSUE TITLE
API Sites: Better display for complex default values

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/grunt-jquery-content#64]
For example when the default value of a widget option is an object.

**Comment by jzaefferer** [comment]
Btw. as a workaround, I've put the defaults for classes in the `<desc>` element as code blocks, e.g. https://github.com/jquery/api.jqueryui.com/commit/f726431292d8ece1baa4cf3dee8ff5dc8f26b015

**Comment by jzaefferer** [comment]
My workaround is bad, since it breaks any programmatic use of our API. There's more usecases for this than just classes.

To make editing the content sane, we should add support for a `<default>` element that replaces the `default` attribute, allowing properly formatted multi-line values.

While we're there, look into a custom transform to remove the indent from multi-line `<code>` and `<example>` elements (and the newly added `<default`), so that we don't have to mess up the indent in the XML file.

**Comment by jzaefferer** [comment]
Fixed this for the new `<default>` element, also improve the styling for the default attribute.
